python slice.py 4 anich_full.jpg Anich
python slice.py 4 artemis_full.jpg Artemis
python slice.py 4 arthetaine_full.jpg Arthetaine
python slice.py 4 bern_north_full.jpg BernNorth
python slice.py 6 lutheran_east_full.jpg LutheranEast
python slice.py 4 lutheran_west_full.jpg LutheranWest
python slice.py 4 shusire_full.jpg Shusire
python slice.py 4 totoiku_full.jpg Totoiku
python slice.py 4 yudia_full.jpg Yudia
python slice.py 5 world_full.jpg World